# Generated by Django 3.2 on 2021-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticanalytics',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='staticanalytics',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='staticanalytics',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
