# Generated by Django 3.2 on 2021-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20210425_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.TextField(blank=True)),
            ],
        ),
    ]
